# Generated by Django 5.0.4 on 2024-05-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_alter_purchaceorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaceorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaceorder',
            name='status',
            field=models.CharField(choices=[('pending,', 'pending'), ('completed,', 'completed'), ('canceled', 'canceled')], max_length=50),
        ),
    ]
