# Generated by Django 5.0.4 on 2024-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_purchaceorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaceorder',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
