# Generated by Django 5.0.4 on 2024-05-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0005_alter_purchaceorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=50),
        ),
    ]
